# https://ci.appveyor.com/project/jakubroztocil/httpie
build: false

environment:
  matrix:
    - PYTHON: "C:/Python27"
    # Python 3.4 has outdated pip
    # - PYTHON: "C:/Python34"
    - PYTHON: "C:/Python36"

init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

install:
  - "%PYTHON%/python.exe -m pip install -U pip"
  - "%PYTHON%/Scripts/pip.exe install -e ."

test_script:
  - "%PYTHON%/Scripts/pip.exe --version"
  - "%PYTHON%/Scripts/http.exe --debug"
  - "%PYTHON%/python.exe setup.py test"
